MAIL_HOST: smtp.mailtrap.io
MAIL_PORT: 2525
MAIL_USERNAME: bb8b0cd460e2c9
MAIL_PASSWORD: c1a9b0c7c12fe6
LARAVEL_ECHO_PORT: 7071
TELEGRAM_BOT: false
TELEGRAM_BOT_TOKEN: '5777518451:AAHRF8GqDMxVkfGcWVuqo4kZXL4OyuC_BNI'
SLACK: true
SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'
NETWORK_TYPE: dhcp
NETWORK_ISEDIT: true
ISEDITED: true
